target-version = "py310"
line-length = 110

[lint]
select = ["E", "F", "I", "W", "UP", "B"]
ignore = ["E501"]  # line-length checked by formatter

[lint.per-file-ignores]
"tests/*" = ["E402", "F401"]
